---
destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    false
markdown:    rdiscount
permalink:   /:year/:month/:day/:title.html
paginate:    6
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
